### ISSUE TITLE
Land Coverages (natural, secondary, transform) 2002, 2009, 2012 by geofences

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-scrum#20]
For each geofence (ea, states, basinSubZones, protectedArea) as shape file according to BioTablero standard.

**Comment by uamoreno** [comment]
Before solving this issue is important to clarify if the required maps must display grouped Coverages as (N, T & S). In that case, several shapefiles must be generated and stored in a new table geo_coverages_**** including a new attribute highlighting the geometry grouping condition for each record by a geofence, for example by Protected Area, dissolving other internal polygons defined on the shapefile given by Jaime.

**Comment by uamoreno** [comment]
In way to provide information for graphs in biotablero de information was loaded into colombia_coverages_details, some new geometries were created in geo_protected_areas and empty rows were deleted.
